### ISSUE TITLE
Hyper Parameter:explore_ratio=0.99999

### ISSUE THREAD

**Issue by YeRen123455** [zxcvfd13502/DDAS_code#1]
Hi Aoming,
thanks for sharing this nice work!
I have two question about search.py.  Looking forward for your reply.
1. Why you set the hyper parameter:explore_ratio as 0.99999 in search.py, which may cause the aug_types being  random chose.
2. In your arxiv paper, you say"We firstly search for augmentation policy on a proxy task with a small network, Wide-ResNet-40-2 [40], on part of the dataset for 20 epochs, with 5000 images for training and 5000 images for validation.". However,  I only get 4000 for training and 500 for validation in search.py.

**Comment by zxcvfd13502** [comment]
Hi,

Thank you for the interest in our work.

1. The augmentation operations are designed to be selected randomly during search.
2. There are some hyper parameter modifications in the following version paper, which will be uploaded to the arxiv recently. Please follow the hyper parameter setting in the code.

**Comment by YeRen123455** [comment]
Thanks

**Comment by YeRen123455** [comment]
Hi Aoming,
sorry for disturbing you.
In your original paper, you derive the equation(9) with equation (1)-(8). Could you please offer the detailed derivation process.
Thanks a lot !

**Comment by YeRen123455** [comment]
Hi Aoming,
There seem to be several differences between the source code (i.e., search.py ) and your original paper.
1. In line 189, search.py.   p.grad = (1 - torch.sigmoid(tp_param).item()) * gt.data   can not reflect the right part of equation (12) .  Maybe it should be replaced as   p.grad = (1 - torch.sigmoid(tp_param).item()/Z) * gt.data?
2. I think you want to to use trace_loss in line 219 search.py to calculate the gradient of gpo and gptp. However, I don't understand how you achieve equation (16)-(17) of your original paper with this line of code.
The above are all my questions about this paper. Look forward to your favourable reply.

**Comment by zxcvfd13502** [comment]
Hi,

As for equation(9), we get it based on equation(5) and equation(6).

As for equation (12), the right part of it actually equals to  (1-p_tp)*L_train, which leads to the implementation form in line 189.

As for line 219, it is computing the gradients in equation (16)-(17) and further compute the gradient wrt. alpha_o and alpha_tp.

**Comment by YeRen123455** [comment]
Thanks a lot！
